### ISSUE TITLE
 kq_init: detected broken kqueue; not using.: Undefined error: 0

### ISSUE THREAD

**Issue by SimonVanherweghe** [wouterverweirder/web-project-validator#3]
Hi Wouter,
I can't get this working.

node: v6.8.0
npm: 3.10.8

```
node app.js https://github.com
createPage https://github.com
status success https://github.com
processing https://github.com with jsdom
processing https://github.com with w3cjs
processing https://github.com with resource loader
13:29:17.679 INFO - Launching a standalone Selenium Server
13:29:17.708 INFO - Java: Oracle Corporation 25.65-b01
13:29:17.709 INFO - OS: Mac OS X 10.12.1 x86_64
13:29:17.721 INFO - v2.53.1, with Core v2.53.1. Built from revision a36b8b1
13:29:17.778 INFO - Driver provider org.openqa.selenium.ie.InternetExplorerDriver registration is skipped:
registration capabilities Capabilities [{ensureCleanSession=true, browserName=internet explorer, version=, platform=WINDOWS}] does not match the current platform MAC
13:29:17.778 INFO - Driver provider org.openqa.selenium.edge.EdgeDriver registration is skipped:
registration capabilities Capabilities [{browserName=MicrosoftEdge, version=, platform=WINDOWS}] does not match the current platform MAC
13:29:17.778 INFO - Driver class not found: com.opera.core.systems.OperaDriver
13:29:17.778 INFO - Driver provider com.opera.core.systems.OperaDriver is not registered
13:29:17.780 INFO - Driver class not found: org.openqa.selenium.htmlunit.HtmlUnitDriver
13:29:17.780 INFO - Driver provider org.openqa.selenium.htmlunit.HtmlUnitDriver is not registered
13:29:17.833 INFO - RemoteWebDriver instances should connect to: http://127.0.0.1:4444/wd/hub
13:29:17.833 INFO - Selenium Server is up and running
13:29:18.662 INFO - Executing: [new session: Capabilities [{rotatable=true, locationContextEnabled=true, loggingPrefs=org.openqa.selenium.logging.LoggingPreferences@3a1bb257, browserName=firefox, javascriptEnabled=true, handlesAlerts=true, requestOrigins={name=webdriverio, version=4.4.0, url=http://webdriver.io}}]])
13:29:18.671 INFO - Creating a new session for Capabilities [{rotatable=true, locationContextEnabled=true, loggingPrefs=org.openqa.selenium.logging.LoggingPreferences@3a1bb257, browserName=firefox, javascriptEnabled=true, handlesAlerts=true, requestOrigins={name=webdriverio, version=4.4.0, url=http://webdriver.io}}]
org.openqa.selenium.firefox.NotConnectedException: Unable to connect to host localhost on port 7055 after 45000 ms. Firefox console output:
obe.com/"},"visible":true,"active":false,"userDisabled":true,"appDisabled":false,"descriptor":"/Library/Application Support/Mozilla/Extensions/{ec8030f7-c20a-464f-9b0e-13a3a9e97384}/web2pdfextension@web2pdf.adobedotcom","installDate":1467285915000,"updateDate":1467285915000,"applyBackgroundUpdates":1,"bootstrap":false,"skinnable":false,"size":167926,"sourceURI":null,"releaseNotesURI":null,"softDisabled":false,"foreignInstall":true,"hasBinaryComponents":false,"strictCompatibility":false,"locales":[],"targetApplications":[{"id":"{ec8030f7-c20a-464f-9b0e-13a3a9e97384}","minVersion":"4.0","maxVersion":"46.0"}],"targetPlatforms":[],"multiprocessCompatible":false,"signedState":2,"seen":true}
1480681759316	DeferredSave.extensions.json	DEBUG	Save changes
1480681759316	addons.xpi	DEBUG	Updating database with changes to installed add-ons
1480681759316	addons.xpi-utils	DEBUG	Updating add-on states
1480681759317	addons.xpi-utils	DEBUG	Writing add-ons list
1480681759318	addons.xpi	DEBUG	Registering manifest for /Applications/Firefox.app/Contents/Resources/browser/features/aushelper@mozilla.org.xpi
1480681759319	addons.xpi	DEBUG	Calling bootstrap method startup on aushelper@mozilla.org version 1.0
1480681759319	addons.xpi	DEBUG	Registering manifest for /Applications/Firefox.app/Contents/Resources/browser/features/e10srollout@mozilla.org.xpi
1480681759319	addons.xpi	DEBUG	Calling bootstrap method startup on e10srollout@mozilla.org version 1.5
1480681759320	addons.xpi	DEBUG	Registering manifest for /Applications/Firefox.app/Contents/Resources/browser/features/firefox@getpocket.com.xpi
1480681759320	addons.xpi	DEBUG	Calling bootstrap method startup on firefox@getpocket.com version 1.0.5
1480681759321	addons.xpi	DEBUG	Registering manifest for /Applications/Firefox.app/Contents/Resources/browser/features/webcompat@mozilla.org.xpi
1480681759321	addons.xpi	DEBUG	Calling bootstrap method startup on webcompat@mozilla.org version 1.0
1480681759322	addons.manager	DEBUG	Registering shutdown blocker for XPIProvider
1480681759323	addons.manager	DEBUG	Provider finished startup: XPIProvider
1480681759323	addons.manager	DEBUG	Starting provider: LightweightThemeManager
1480681759323	addons.manager	DEBUG	Registering shutdown blocker for LightweightThemeManager
1480681759323	addons.manager	DEBUG	Provider finished startup: LightweightThemeManager
1480681759324	addons.manager	DEBUG	Starting provider: GMPProvider
1480681759330	addons.manager	DEBUG	Registering shutdown blocker for GMPProvider
1480681759330	addons.manager	DEBUG	Provider finished startup: GMPProvider
1480681759330	addons.manager	DEBUG	Starting provider: PluginProvider
1480681759330	addons.manager	DEBUG	Registering shutdown blocker for PluginProvider
1480681759330	addons.manager	DEBUG	Provider finished startup: PluginProvider
1480681759330	addons.manager	DEBUG	Completed startup sequence
1480681759621	addons.manager	DEBUG	Starting provider: <unnamed-provider>
1480681759622	addons.manager	DEBUG	Registering shutdown blocker for <unnamed-provider>
1480681759622	addons.manager	DEBUG	Provider finished startup: <unnamed-provider>
1480681759706	DeferredSave.extensions.json	DEBUG	Write succeeded
1480681759706	addons.xpi-utils	DEBUG	XPI Database saved, setting schema version preference to 17
1480681759706	DeferredSave.extensions.json	DEBUG	Starting timer
1480681759724	addons.repository	DEBUG	No addons.json found.
1480681759724	DeferredSave.addons.json	DEBUG	Save changes
1480681759726	DeferredSave.addons.json	DEBUG	Starting timer
1480681759749	addons.manager	DEBUG	Starting provider: PreviousExperimentProvider
1480681759749	addons.manager	DEBUG	Registering shutdown blocker for PreviousExperimentProvider
1480681759749	addons.manager	DEBUG	Provider finished startup: PreviousExperimentProvider
1480681759752	DeferredSave.extensions.json	DEBUG	Starting write
1480681759773	DeferredSave.extensions.json	DEBUG	Write succeeded
1480681759778	DeferredSave.addons.json	DEBUG	Starting write
1480681759788	DeferredSave.addons.json	DEBUG	Write succeeded
[warn] kq_init: detected broken kqueue; not using.: Undefined error: 0
at org.openqa.selenium.firefox.internal.NewProfileExtensionConnection.start(NewProfileExtensionConnection.java:112)
	at org.openqa.selenium.firefox.FirefoxDriver.startClient(FirefoxDriver.java:271)
	at org.openqa.selenium.remote.RemoteWebDriver.<init>(RemoteWebDriver.java:119)
	at org.openqa.selenium.firefox.FirefoxDriver.<init>(FirefoxDriver.java:218)
	at org.openqa.selenium.firefox.FirefoxDriver.<init>(FirefoxDriver.java:211)
	at org.openqa.selenium.firefox.FirefoxDriver.<init>(FirefoxDriver.java:129)
	at sun.reflect.NativeConstructorAccessorImpl.newInstance0(Native Method)
	at sun.reflect.NativeConstructorAccessorImpl.newInstance(NativeConstructorAccessorImpl.java:62)
	at sun.reflect.DelegatingConstructorAccessorImpl.newInstance(DelegatingConstructorAccessorImpl.java:45)
	at java.lang.reflect.Constructor.newInstance(Constructor.java:422)
	at org.openqa.selenium.remote.server.FirefoxDriverProvider.callConstructor(FirefoxDriverProvider.java:91)
	at org.openqa.selenium.remote.server.FirefoxDriverProvider.newInstance(FirefoxDriverProvider.java:68)
	at org.openqa.selenium.remote.server.DefaultDriverFactory.newInstance(DefaultDriverFactory.java:60)
	at org.openqa.selenium.remote.server.DefaultSession$BrowserCreator.call(DefaultSession.java:222)
	at org.openqa.selenium.remote.server.DefaultSession$BrowserCreator.call(DefaultSession.java:1)
	at java.util.concurrent.FutureTask.run(FutureTask.java:266)
	at org.openqa.selenium.remote.server.DefaultSession$1.run(DefaultSession.java:176)
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1142)
at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:617)
at java.lang.Thread.run(Thread.java:745)
```

**Comment by wouterverweirder** [comment]
Looks like selenium 2.x (used by webdriverio) is not compatible with latest version of Firefox. https://github.com/webdriverio/webdriverio/issues/1605

**Comment by wouterverweirder** [comment]
Will need to take a look at https://github.com/mozilla/geckodriver

**Comment by wouterverweirder** [comment]
https://github.com/vladikoff/node-geckodriver might be interesting to automate geckodriver config

**Comment by wouterverweirder** [comment]
nope, that's a crappy, fixed-version downloader.

**Comment by wouterverweirder** [comment]
@SimonVanherweghe can you check latest version in dev branch & let me know if you still run into this issue?

**Comment by SimonVanherweghe** [comment]
Nope, it's fixed, thanks
