### ISSUE TITLE
internal/modules/cjs/loader.js:605

### ISSUE THREAD

**Issue by frederiekberthier** [wouterverweirder/web-project-validator#9]
I get an error when running the command: 
C:\Users\frederiek.berthier>node app.js https://www.howest.be

Error message is

internal/modules/cjs/loader.js:605
    throw err;
    ^

Error: Cannot find module 'C:\Users\frederiek.berthier\app.js'
    at Function.Module._resolveFilename (internal/modules/cjs/loader.js:603:15)
    at Function.Module._load (internal/modules/cjs/loader.js:529:25)
    at Function.Module.runMain (internal/modules/cjs/loader.js:774:12)
    at executeUserCode (internal/bootstrap/node.js:342:17)
    at startExecution (internal/bootstrap/node.js:276:5)
    at startup (internal/bootstrap/node.js:227:5)
    at bootstrapNodeJSCore (internal/bootstrap/node.js:743:3)

**Comment by SimonVanherweghe** [comment]
You should run it in the project directory (there is no app.js in your home directory)

**Comment by frederiekberthier** [comment]
Same error.

C:\MAMP\htdocs\webvalidator>node app.js http://www.howest.be
internal/modules/cjs/loader.js:605
    throw err;
    ^

Error: Cannot find module 'yargs'
    at Function.Module._resolveFilename (internal/modules/cjs/loader.js:603:15)
    at Function.Module._load (internal/modules/cjs/loader.js:529:25)
    at Module.require (internal/modules/cjs/loader.js:657:17)
    at require (internal/modules/cjs/helpers.js:22:18)
    at Object.<anonymous> (C:\MAMP\htdocs\webvalidator\app.js:3:14)
    at Module._compile (internal/modules/cjs/loader.js:721:30)
    at Object.Module._extensions..js (internal/modules/cjs/loader.js:732:10)
    at Module.load (internal/modules/cjs/loader.js:620:32)
    at tryModuleLoad (internal/modules/cjs/loader.js:560:12)
    at Function.Module._load (internal/modules/cjs/loader.js:552:3)

**Comment by wouterverweirder** [comment]
did you run npm install or yarn to install the dependencies?
